const { MessageEmbed } = require('discord.js')

module.exports = {
    name: "gay",
    data: {
        name: "gay",
        description: "The bot tells you how gay you are obviously the numbers are random",
    },
        execute(interaction){
            var embed1 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**1%**")
            var embed2 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**2%**")
            var embed3 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("** Sei gay al:**")
            .setDescription("**3%**")
            var embed4 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**4%**")
            var embed5 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**5%**")
            var embed6 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**6%**")
            var embed7 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**7%**")
            var embed8 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**8%**")
            var embed9 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**9%**")
            var embed10 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**10%**")
            var embed11 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**11%**")
            var embed12 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**12%**")
            var embed13 = new MessageEmbed() 
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**13%**")
            var embed14 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**14%**")
            var embed15 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**15%**")
            var embed16 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**16%**")
            var embed17 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**17%**")
            var embed18 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**18%**")
            var embed19 = new MessageEmbed() 
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**19%**")
            var embed20 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**20%**")
            var embed21 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**21%**")
            var embed22 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**22%**")
            var embed23 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**23%**")
            var embed24 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**24%**")
            var embed25 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**25%**")
            var embed26 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**26%**")
            var embed27 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**27%**")
            var embed28 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**28%**")
            var embed29 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**29%**")
            var embed30 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**30%**")
            var embed31 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**31%**")
            var embed32 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**32%**")
            var embed33 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**33%**")
            var embed34 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**34%**")
            var embed35 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**35%**")
            var embed36 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**36%**")
            var embed37 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**37%**")
            var embed38 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**38%**")
            var embed39 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**39%**")
            var embed40 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**40%**")
            var embed41 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**41%**")
            var embed42 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**52%**")
            var embed43 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**43%**")
            var embed44 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**44%**")
            var embed45 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**45%**")
            var embed46 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**46%**")
            var embed47 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**47%**")
            var embed48 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**48%**")
            var embed49 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**49%**")
            var embed50 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**50%**")
            var embed51 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**51%**")
            var embed52 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**52%**")
            var embed53 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**53%**")
            var embed54 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**54%**")
            var embed55 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**55%**")
            var embed56 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**56%**")
            var embed57 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**57%**")
            var embed58 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**58%**")
            var embed59 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**59%**")
            var embed60 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**60%**")
            var embed61 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**61%**")
            var embed62 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**62%**")
            var embed63 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**63%**")
            var embed64 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**64%**")
            var embed65 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**65%**")
            var embed66 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**66%**")
            var embed67 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**67%**")
            var embed68 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**68%**")
            var embed69 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**69%**")
            var embed70 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**70%**")
            var embed71 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**71%**")
            var embed72 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**72%**")
            var embed73 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**73%**")
            var embed74 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**74%**")
            var embed75 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**75%**")
            var embed76 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**76%**")
            var embed77 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**77%**")
            var embed78 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**78%**")
            var embed79 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**79%**")
            var embed80 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**80%**")
            var embed81 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**81%**")
            var embed82 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**82%**")
            var embed83 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**83%**")
            var embed84 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**84%**")
            var embed85 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**85%**")
            var embed86 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**86%**")
            var embed87 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**87%**")
            var embed88 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**88%**")
            var embed89 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**89%**")
            var embed90 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**90%**")
            var embed91 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**91%**")
            var embed92 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**92%**")
            var embed93 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**93%**")
            var embed94 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**94%**")
            var embed95 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**95%**")
            var embed96 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**96%**")
            var embed97 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**97%**")
            var embed98 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**98%**")
            var embed99 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**99%**")
            var embed100 = new MessageEmbed()
            .setColor("DARK_PURPLE")
            .setTitle("You are Gay Al")
            .setDescription("**100%**")
            var messaggi = [embed1, embed2, embed3, embed4, embed5, embed6, embed7, embed8, embed9, embed10, embed11, embed12, embed13, embed14, embed15, embed16, embed17, embed18, embed19, embed20, embed21, embed22, embed23, embed24, embed25, embed26, embed27, embed28, embed29, embed30, embed31, embed32, embed33, embed34, embed35, embed36, embed37, embed38, embed39, embed40, embed41, embed42, embed43, embed44, embed45, embed46, embed47, embed48, embed49, embed50, embed51, embed52, embed53, embed54, embed55, embed56, embed57, embed58, embed59, embed60, embed61, embed62, embed63, embed64, embed65, embed66, embed67, embed68, embed69, embed70, embed71, embed72, embed73, embed74, embed75, embed76, embed77, embed78, embed79, embed80, embed81, embed82, embed83, embed84, embed85, embed86, embed87, embed88, embed89, embed90, embed91, embed92, embed93, embed94, embed95, embed96, embed97, embed98, embed99, embed100 ]
            interaction.reply({ embeds: [messaggi[Math.floor(Math.random() * messaggi.length)]] });
        
    
        }
    }
